<?php

declare(strict_types=1);

namespace QBitFlow\Tests\Unit;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use QBitFlow\Exceptions\ValidationException;
use QBitFlow\Webhooks\WebhookVerifier;

/**
 * Local webhook signature verification.
 *
 * The reference vectors below were generated by the Go SDK, which canonicalises with the
 * same `encoding/json` the QBitFlow API itself uses. Asserting against them keeps all four
 * SDKs byte-identical: if this SDK's canonical form or signature ever drifts from Go's,
 * these fail rather than silently rejecting genuine webhooks in production.
 */
final class WebhookVerifierTest extends TestCase
{
	private const SECRET = 'whsec_test_0123456789abcdef';
	private const TIMESTAMP = '1700000000';

	/** @return array<string,array{0:string,1:string,2:string}> */
	public static function referenceVectors(): array
	{
		return [
			'arrayOrder' => ['{"items":[3,1,2]}', '{"items":[3,1,2]}', 'sha256=8270d9e92c09c45b1ef5b4ec50e32e2b1c3fea8a7f49947d6af0fee131854d27'],
			'emptyObj' => ['{}', '{}', 'sha256=86e42664e55bdef9d21c29ec99ef840bb60f05f718392629bb0eb162a585147e'],
			'html' => ['{"url":"https://x.test/a?b=1&c=2","tag":"<b>"}', '{"tag":"\\u003cb\\u003e","url":"https://x.test/a?b=1\\u0026c=2"}', 'sha256=28b274c01275f3ea7c03f3feb7fd2ec52a9594333779cae66f975d8914bc9383'],
			'nested' => ['{"z":{"y":1,"x":2},"a":[{"d":4,"c":3}]}', '{"a":[{"c":3,"d":4}],"z":{"x":2,"y":1}}', 'sha256=710b9fed39bfd9f5c087f26f4bbb91eb5a30a56fc8e2f8e4ba41c0b92b7949a7'],
			'nulls' => ['{"a":null,"b":false,"c":true}', '{"a":null,"b":false,"c":true}', 'sha256=2cdc9b14b681f7f80c7f4308cfe4a080840c16db5e2a2fca46e8d2a9e99677b8'],
			'numbers' => ['{"int":2592000,"float":9.99,"zero":0,"neg":-1.5}', '{"float":9.99,"int":2592000,"neg":-1.5,"zero":0}', 'sha256=d7939b32907de3fdfb5db88092caf53aa58234e3ec62ca9813d24df4bab78d3e'],
			'realWebhook' => ['{"uuid":"pay@01a0c0c7","txType":"payment","status":{"status":"completed","txHash":"0xabc"},"managementPageLink":"https://qbitflow.app/m?id=1&k=2"}', '{"managementPageLink":"https://qbitflow.app/m?id=1\\u0026k=2","status":{"status":"completed","txHash":"0xabc"},"txType":"payment","uuid":"pay@01a0c0c7"}', 'sha256=bdce3332c824b8abbe798034e6f8156d914c81c088aad6f5694df3b98241c540'],
			'simple' => ['{"a":1,"b":2}', '{"a":1,"b":2}', 'sha256=7293f8a9be38cc10138c04b2ca50bb65533bf356f476552981079eebf7b3a53a'],
			'unicode' => ['{"name":"Café Crème 日本語"}', '{"name":"Café Crème 日本語"}', 'sha256=8828459bb4f050a0ae4d633d71edefa6027c1cc39933e8b27de9bc5fafd491ac'],
			'unsorted' => ['{"b":2,"a":1,"c":3}', '{"a":1,"b":2,"c":3}', 'sha256=cefa417c919e24dadad16670fb997f379aece68be25f46d70bd2ee6541bb7b0a'],
			'wholeFloats' => ['{"whole":1.0,"negWhole":-2.0,"frac":2.50}', '{"frac":2.5,"negWhole":-2,"whole":1}', 'sha256=568f803efa06262d9bc43020a326a2d335739bc54c2f1f546d2f0c4d7ac70619'],
		];
	}

	#[Test]
	#[DataProvider('referenceVectors')]
	public function it_canonicalises_identically_to_go(string $input, string $canonical, string $signature): void
	{
		$this->assertSame($canonical, WebhookVerifier::canonicalJson($input));
	}

	#[Test]
	#[DataProvider('referenceVectors')]
	public function it_signs_identically_to_go(string $input, string $canonical, string $signature): void
	{
		$this->assertSame(
			$signature,
			WebhookVerifier::computeSignature(self::SECRET, self::TIMESTAMP, $input)
		);
	}

	#[Test]
	public function it_sorts_keys_at_every_level(): void
	{
		$this->assertSame('{"a":1,"b":2}', WebhookVerifier::canonicalJson('{"b":2,"a":1}'));
		$this->assertSame('{"z":{"x":2,"y":1}}', WebhookVerifier::canonicalJson('{"z":{"y":1,"x":2}}'));
	}

	#[Test]
	public function it_preserves_array_order(): void
	{
		// Arrays are ordered by definition: sorting them would change meaning.
		$this->assertSame('{"items":[3,1,2]}', WebhookVerifier::canonicalJson('{"items":[3,1,2]}'));
	}

	#[Test]
	public function it_keeps_an_empty_object_distinct_from_an_empty_array(): void
	{
		// Decoding with assoc=true would turn {} into [] and change the signed bytes.
		$this->assertSame('{}', WebhookVerifier::canonicalJson('{}'));
		$this->assertSame('[]', WebhookVerifier::canonicalJson('[]'));
		$this->assertSame('{"a":{},"b":[]}', WebhookVerifier::canonicalJson('{"b":[],"a":{}}'));
	}

	#[Test]
	public function it_rejects_invalid_json(): void
	{
		$this->expectException(ValidationException::class);
		WebhookVerifier::canonicalJson('{not json');
	}

	#[Test]
	public function it_accepts_a_genuine_webhook(): void
	{
		$ts = (string) time();
		$payload = '{"uuid":"pay@abc","txType":"payment"}';
		$sig = WebhookVerifier::computeSignature(self::SECRET, $ts, $payload);

		WebhookVerifier::verify(self::SECRET, $ts, $sig, $payload);
		$this->addToAssertionCount(1);
	}

	#[Test]
	public function it_accepts_a_payload_whose_keys_were_reordered(): void
	{
		$ts = (string) time();
		$sig = WebhookVerifier::computeSignature(self::SECRET, $ts, '{"a":1,"b":2}');

		WebhookVerifier::verify(self::SECRET, $ts, $sig, '{"b":2,"a":1}');
		$this->addToAssertionCount(1);
	}

	#[Test]
	public function it_rejects_a_tampered_payload(): void
	{
		$ts = (string) time();
		$sig = WebhookVerifier::computeSignature(self::SECRET, $ts, '{"uuid":"pay@abc"}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('signature mismatch');
		WebhookVerifier::verify(self::SECRET, $ts, $sig, '{"uuid":"pay@EVIL"}');
	}

	#[Test]
	public function it_rejects_a_tampered_timestamp(): void
	{
		$ts = time();
		$sig = WebhookVerifier::computeSignature(self::SECRET, (string) $ts, '{"a":1}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('signature mismatch');
		WebhookVerifier::verify(self::SECRET, (string) ($ts - 30), $sig, '{"a":1}');
	}

	#[Test]
	public function it_rejects_the_wrong_secret(): void
	{
		$ts = (string) time();
		$sig = WebhookVerifier::computeSignature(self::SECRET, $ts, '{"a":1}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('signature mismatch');
		WebhookVerifier::verify('whsec_wrong', $ts, $sig, '{"a":1}');
	}

	#[Test]
	public function it_rejects_a_replayed_webhook(): void
	{
		$old = (string) (time() - 600);
		$sig = WebhookVerifier::computeSignature(self::SECRET, $old, '{"a":1}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('expired');
		WebhookVerifier::verify(self::SECRET, $old, $sig, '{"a":1}');
	}

	#[Test]
	public function it_rejects_a_future_timestamp(): void
	{
		// Guards against a forged future timestamp extending the replay window.
		$future = (string) (time() + 600);
		$sig = WebhookVerifier::computeSignature(self::SECRET, $future, '{"a":1}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('expired');
		WebhookVerifier::verify(self::SECRET, $future, $sig, '{"a":1}');
	}

	#[Test]
	public function it_honours_a_custom_replay_window(): void
	{
		$old = (string) (time() - 600);
		$sig = WebhookVerifier::computeSignature(self::SECRET, $old, '{"a":1}');

		WebhookVerifier::verify(self::SECRET, $old, $sig, '{"a":1}', 1800);
		$this->addToAssertionCount(1);
	}

	#[Test]
	public function it_rejects_a_non_numeric_timestamp(): void
	{
		$this->expectException(ValidationException::class);
		WebhookVerifier::verify(self::SECRET, 'nope', 'sha256=abc', '{"a":1}');
	}

	#[Test]
	public function it_extracts_headers_from_a_server_superglobal(): void
	{
		// PHP mangles header names into $_SERVER as HTTP_X_WEBHOOK_*.
		$h = WebhookVerifier::extractHeaders([
			'HTTP_X_WEBHOOK_SIGNATURE_256' => 'sha256=abc',
			'HTTP_X_WEBHOOK_TIMESTAMP' => '1700000000',
			'HTTP_X_WEBHOOK_ID' => 'pay@abc',
			'REQUEST_METHOD' => 'POST',
		]);

		$this->assertSame('sha256=abc', $h['signature']);
		$this->assertSame('1700000000', $h['timestamp']);
		$this->assertSame('pay@abc', $h['webhookId']);
		$this->assertFalse($h['isTest']);
	}

	#[Test]
	public function it_extracts_headers_from_a_psr7_style_array(): void
	{
		$h = WebhookVerifier::extractHeaders([
			'X-Webhook-Signature-256' => ['sha256=abc'],
			'X-Webhook-Timestamp' => ['1700000000'],
			'X-Webhook-Id' => [WebhookVerifier::TEST_WEBHOOK_ID],
		]);

		$this->assertSame('sha256=abc', $h['signature']);
		$this->assertTrue($h['isTest']);
	}

	#[Test]
	public function missing_headers_come_back_empty(): void
	{
		$h = WebhookVerifier::extractHeaders([]);

		$this->assertSame('', $h['signature']);
		$this->assertSame('', $h['timestamp']);
		$this->assertFalse($h['isTest']);
	}
}
