<?php

declare(strict_types=1);

namespace QBitFlow\Tests\Unit;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use QBitFlow\Exceptions\ValidationException;
use QBitFlow\Webhooks\WebhookVerifier;

/**
 * Local webhook signature verification.
 *
 * The reference vectors below were generated by the Go SDK, which canonicalises with the
 * same `encoding/json` the QBitFlow API itself uses. Asserting against them keeps all four
 * SDKs byte-identical: if this SDK's canonical form or signature ever drifts from Go's,
 * these fail rather than silently rejecting genuine webhooks in production.
 */
final class WebhookVerifierTest extends TestCase
{
	private const SECRET = 'whsec_test_0123456789abcdef';
	private const TIMESTAMP = '1700000000';

	/** @return array<string,array{0:string,1:string,2:string}> */
	public static function referenceVectors(): array
	{
		return [
			'arrayOrder' => ['{"items":[3,1,2]}', '{"items":[3,1,2]}', 'sha256=8270d9e92c09c45b1ef5b4ec50e32e2b1c3fea8a7f49947d6af0fee131854d27'],
			'emptyObj' => ['{}', '{}', 'sha256=86e42664e55bdef9d21c29ec99ef840bb60f05f718392629bb0eb162a585147e'],
			'html' => ['{"url":"https://x.test/a?b=1&c=2","tag":"<b>"}', '{"tag":"\\u003cb\\u003e","url":"https://x.test/a?b=1\\u0026c=2"}', 'sha256=28b274c01275f3ea7c03f3feb7fd2ec52a9594333779cae66f975d8914bc9383'],
			'nested' => ['{"z":{"y":1,"x":2},"a":[{"d":4,"c":3}]}', '{"a":[{"c":3,"d":4}],"z":{"x":2,"y":1}}', 'sha256=710b9fed39bfd9f5c087f26f4bbb91eb5a30a56fc8e2f8e4ba41c0b92b7949a7'],
			'nulls' => ['{"a":null,"b":false,"c":true}', '{"a":null,"b":false,"c":true}', 'sha256=2cdc9b14b681f7f80c7f4308cfe4a080840c16db5e2a2fca46e8d2a9e99677b8'],
			'numbers' => ['{"int":2592000,"float":9.99,"zero":0,"neg":-1.5}', '{"float":9.99,"int":2592000,"neg":-1.5,"zero":0}', 'sha256=d7939b32907de3fdfb5db88092caf53aa58234e3ec62ca9813d24df4bab78d3e'],
			'realWebhook' => ['{"uuid":"pay@01a0c0c7","txType":"payment","status":{"status":"completed","txHash":"0xabc"},"managementPageLink":"https://qbitflow.app/m?id=1&k=2"}', '{"managementPageLink":"https://qbitflow.app/m?id=1\\u0026k=2","status":{"status":"completed","txHash":"0xabc"},"txType":"payment","uuid":"pay@01a0c0c7"}', 'sha256=bdce3332c824b8abbe798034e6f8156d914c81c088aad6f5694df3b98241c540'],
			'simple' => ['{"a":1,"b":2}', '{"a":1,"b":2}', 'sha256=7293f8a9be38cc10138c04b2ca50bb65533bf356f476552981079eebf7b3a53a'],
			'unicode' => ['{"name":"Café Crème 日本語"}', '{"name":"Café Crème 日本語"}', 'sha256=8828459bb4f050a0ae4d633d71edefa6027c1cc39933e8b27de9bc5fafd491ac'],
			'unsorted' => ['{"b":2,"a":1,"c":3}', '{"a":1,"b":2,"c":3}', 'sha256=cefa417c919e24dadad16670fb997f379aece68be25f46d70bd2ee6541bb7b0a'],
			'wholeFloats' => ['{"whole":1.0,"negWhole":-2.0,"frac":2.50}', '{"frac":2.5,"negWhole":-2,"whole":1}', 'sha256=568f803efa06262d9bc43020a326a2d335739bc54c2f1f546d2f0c4d7ac70619'],
		];
	}

	#[Test]
	#[DataProvider('referenceVectors')]
	public function it_canonicalises_identically_to_go(string $input, string $canonical, string $signature): void
	{
		$this->assertSame($canonical, WebhookVerifier::canonicalJson($input));
	}

	#[Test]
	#[DataProvider('referenceVectors')]
	public function it_signs_identically_to_go(string $input, string $canonical, string $signature): void
	{
		$this->assertSame(
			$signature,
			WebhookVerifier::computeSignature(self::SECRET, self::TIMESTAMP, $input)
		);
	}

	/**
	 * Golden vectors shared by all four SDKs, generated by the Go SDK against the
	 * `encoding/json` rules the QBitFlow API itself uses. Each carries its own secret and
	 * timestamp. They exercise the corner cases that differ between JSON encoders: key
	 * order (by UTF-8 bytes), HTML and U+2028/9 escaping, C0 controls, lone surrogates,
	 * float64 number formatting (`1e21`, integers above 2^53, `100.0` → `100`, `-0`),
	 * decimal strings of 19+ digits staying strings, empty containers, and real webhook
	 * envelopes. Non-ASCII characters are written as `\u{…}` escapes; the bytes are Go's.
	 *
	 * @return array<string,array{0:string,1:string,2:string,3:string,4:string}>
	 */
	public static function goldenVectors(): array
	{
		return [
			'empty_object' => ['{}', 'whsec_golden_secret_0123456789', '1758540000', '{}', 'sha256=122d17b8a94e9170db2d91edb1a4060a1847a8de8020e3a1a20ea84293f28d22'],
			'key_order_and_types' => ['{"zeta":1,"alpha":"a","Beta":true,"nested":{"y":null,"x":[1,2,{"b":"B","a":"A"}]},"émoji":"☕"}', 'whsec_golden_secret_0123456789', '1758540000', '{"Beta":true,"alpha":"a","nested":{"x":[1,2,{"a":"A","b":"B"}],"y":null},"zeta":1,"émoji":"☕"}', 'sha256=078c8862e2a4b67245ff3c04405d313c1815d19e3f246446583919260df7332d'],
			'html_and_unicode_escaping' => ['{"msg":"<b>ok</b> & done / fine \\"q\\" \\\\ back","line":"a b c\\ttab\\nnl","dq":"<script>"}', 'whsec_golden_secret_0123456789', '1758540000', '{"dq":"\\u003cscript\\u003e","line":"a\\u2028b\\u2029c\\ttab\\nnl","msg":"\\u003cb\\u003eok\\u003c/b\\u003e \\u0026 done / fine \\"q\\" \\\\ back"}', 'sha256=220a10812e56a3cd202440cdbe7fa255515979760c4d15f821b3a6fea34564a4'],
			'numbers_float64_semantics' => ['{"n":[1e-7,1e-6,0.00001234,0.0001234,0.001,1e15,1e16,1e20,1e21,1.5e22,123456789.123,0.1,100.0,10.5,0,5e-324,1.7976931348623157e308,9007199254740993,2.5e-5,1234567890123456789,19.99,-5]}', 'whsec_golden_secret_0123456789', '1758540000', '{"n":[1e-7,0.000001,0.00001234,0.0001234,0.001,1000000000000000,10000000000000000,100000000000000000000,1e+21,1.5e+22,123456789.123,0.1,100,10.5,0,5e-324,1.7976931348623157e+308,9007199254740992,0.000025,1234567890123456800,19.99,-5]}', 'sha256=2969a1f1c606f2cefbc8dadef939ccf2337d0388827819c888137454deec56b8'],
			'empty_containers' => ['{"emptyObj":{},"emptyArr":[],"list":[{},[],[[]],[{}]],"s":""}', 'whsec_golden_secret_0123456789', '1758540000', '{"emptyArr":[],"emptyObj":{},"list":[{},[],[[]],[{}]],"s":""}', 'sha256=de1584470053d814ee8903db86fbe07517e13a0282c1e682587ed77659f9231a'],
			'transaction_webhook' => ['{"uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695","txType":"payment","status":{"status":"completed","txHash":"0x9f2c","settlementDetails":{"feeBps":100,"txMetadata":{"networkFees":{"amount":"21000","unitsConsumed":21000},"blockData":{"number":"1234567","timestamp":1758539990},"mainCurrencyPriceUSD":0.00001234},"txAmounts":{"usd":{"platform":0.2,"merchant":19.79},"minUnits":{"platform":"200000","organization":"0","referral":"0","merchant":"19790000"}}}},"session":{"uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695","reference":"ORD/2026/17","productId":42,"productName":"Café Premium","description":"Best <coffee> & tea","price":19.99,"successUrl":"https://shop.example.com/ok?o=17&x=1","organizationId":7,"organizationName":"Acme","feeBps":100,"userId":0,"test":false,"customerUUID":"3f2b1c1e-8d1a-4c2b-9b0e-1a2b3c4d5e6f","txType":"payment","availableCurrencies":[1,2,3]},"managementPageLink":"https://app.qbitflow.app/m/abc"}', 'whsec_golden_secret_0123456789', '1758540000', '{"managementPageLink":"https://app.qbitflow.app/m/abc","session":{"availableCurrencies":[1,2,3],"customerUUID":"3f2b1c1e-8d1a-4c2b-9b0e-1a2b3c4d5e6f","description":"Best \\u003ccoffee\\u003e \\u0026 tea","feeBps":100,"organizationId":7,"organizationName":"Acme","price":19.99,"productId":42,"productName":"Café Premium","reference":"ORD/2026/17","successUrl":"https://shop.example.com/ok?o=17\\u0026x=1","test":false,"txType":"payment","userId":0,"uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695"},"status":{"settlementDetails":{"feeBps":100,"txAmounts":{"minUnits":{"merchant":"19790000","organization":"0","platform":"200000","referral":"0"},"usd":{"merchant":19.79,"platform":0.2}},"txMetadata":{"blockData":{"number":"1234567","timestamp":1758539990},"mainCurrencyPriceUSD":0.00001234,"networkFees":{"amount":"21000","unitsConsumed":21000}}},"status":"completed","txHash":"0x9f2c"},"txType":"payment","uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695"}', 'sha256=c6e845486a0c5d2b9f3d1fca4a9c4190649ed46b06db74d71bd2703358a411ec'],
			'subscription_billing_webhook' => ['{"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","subscriptionReference":"plan-pro","type":"billing","data":{"uuid":"sub-hist@01a0c5be-0000-7000-8000-000000000002","createdAt":"2026-09-21T22:02:09.986381+02:00","from":"0xfrom","to":"0xto","amount":9.99,"amountMinUnits":"9990000","currencyId":2,"test":true,"transactionHash":"0xhash","organizationId":7,"userId":3,"name":"Pro","description":"Monthly","productId":9,"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","metadata":{"feeBps":100,"txMetadata":{"networkFees":{"amount":"0","unitsConsumed":0},"blockData":{"number":"","timestamp":0}},"txAmounts":{"usd":{"platform":0.0999,"merchant":9.8901},"minUnits":{"platform":"99900","organization":"0","referral":"0","merchant":"9890100"}}}}}', 'whsec_golden_secret_0123456789', '1758540000', '{"data":{"amount":9.99,"amountMinUnits":"9990000","createdAt":"2026-09-21T22:02:09.986381+02:00","currencyId":2,"description":"Monthly","from":"0xfrom","metadata":{"feeBps":100,"txAmounts":{"minUnits":{"merchant":"9890100","organization":"0","platform":"99900","referral":"0"},"usd":{"merchant":9.8901,"platform":0.0999}},"txMetadata":{"blockData":{"number":"","timestamp":0},"networkFees":{"amount":"0","unitsConsumed":0}}},"name":"Pro","organizationId":7,"productId":9,"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","test":true,"to":"0xto","transactionHash":"0xhash","userId":3,"uuid":"sub-hist@01a0c5be-0000-7000-8000-000000000002"},"subscriptionReference":"plan-pro","subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","type":"billing"}', 'sha256=c69da12a34355745027c9db89877cdd8187df497171c2ee591bf7a80abd36187'],
			'status_transition_webhook' => ['{"type":"status_transition","subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","data":{"previousStatus":"active","currentStatus":"low_on_funds","updatedAt":"2026-09-22T10:00:00Z"}}', 'whsec_golden_secret_0123456789', '1758540000', '{"data":{"currentStatus":"low_on_funds","previousStatus":"active","updatedAt":"2026-09-22T10:00:00Z"},"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","type":"status_transition"}', 'sha256=88708bfd796485695fd051a03a32ee3374ecf7b02ead27b1bbcf67504380f46a'],
			// Added 2026-09-23, generated by the Go SDK (scratch golden/vectors-new.json).
			"decimal strings of 19+ digits stay strings" => ["{\"amountMinUnits\":\"1000000000000000000\",\"txAmounts\":{\"minUnits\":{\"merchant\":\"99000000000000000000\",\"platform\":\"1000000000000000000000\",\"referral\":\"0\"}},\"big\":12345678901234567890,\"id\":\"0001\",\"neg\":\"-12345678901234567890\"}", "whsec_golden_secret_0123456789", "1758540000", "{\"amountMinUnits\":\"1000000000000000000\",\"big\":12345678901234567000,\"id\":\"0001\",\"neg\":\"-12345678901234567890\",\"txAmounts\":{\"minUnits\":{\"merchant\":\"99000000000000000000\",\"platform\":\"1000000000000000000000\",\"referral\":\"0\"}}}", "sha256=88423199655b9f5e5db5e4b4fbdaea52d61f64f08837cad0a65bab1ea87b6a19"],
			"control characters" => ["{\"s\":\"a\\bb\\fc\\u0000d\\u001fe\\u007ff\\u0080g\",\"k\\u0001\":\"x\",\"tab\":\"\\t\",\"cr\":\"\\r\"}", "whsec_golden_secret_0123456789", "1758540000", "{\"cr\":\"\\r\",\"k\\u0001\":\"x\",\"s\":\"a\\bb\\fc\\u0000d\\u001fe\u{007F}f\u{0080}g\",\"tab\":\"\\t\"}", "sha256=4118c0a289dd2e4bb4ab62ad2b13a7e1ff60981717c75d6c1ce1c4848e82d5f0"],
			"lone surrogates become U+FFFD" => ["{\"hi\":\"\\ud800x\",\"lo\":\"\\udfff\",\"pair\":\"\u{1F600}\"}", "whsec_golden_secret_0123456789", "1758540000", "{\"hi\":\"\u{FFFD}x\",\"lo\":\"\u{FFFD}\",\"pair\":\"\u{1F600}\"}", "sha256=b31ca0014545f32bf62e937955fe50e11c5a6cf68f57052008edd0cfb2af29d3"],
			"negative zero and exponent forms" => ["{\"a\":-0,\"b\":-0.0,\"c\":1E2,\"d\":1e-7,\"e\":-1.5e-10,\"f\":0.0,\"g\":-0.000001}", "whsec_golden_secret_0123456789", "1758540000", "{\"a\":-0,\"b\":-0,\"c\":100,\"d\":1e-7,\"e\":-1.5e-10,\"f\":0,\"g\":-0.000001}", "sha256=45e3033a130332ab91bce58115d670ac83a9d4a41b59f51323c4e20625bcd2bc"],
			"keys are ordered by UTF-8 bytes" => ["{\"\u{1F600}\":1,\"\u{FFFF}\":2,\"a\":3,\"\u{00E9}\":4,\"Z\":5,\"\":6,\"aa\":7,\"a\\u0000\":8}", "whsec_golden_secret_0123456789", "1758540000", "{\"\":6,\"Z\":5,\"a\":3,\"a\\u0000\":8,\"aa\":7,\"\u{00E9}\":4,\"\u{FFFF}\":2,\"\u{1F600}\":1}", "sha256=3b3885769c26eac4d862579cb4782135f5021d1ba5fa6c801d50f9228c164fb9"],
		];
	}

	#[Test]
	#[DataProvider('goldenVectors')]
	public function it_canonicalises_the_shared_golden_vectors(string $payload, string $secret, string $timestamp, string $canonical, string $signature): void
	{
		$this->assertSame($canonical, WebhookVerifier::canonicalJson($payload));
	}

	#[Test]
	#[DataProvider('goldenVectors')]
	public function it_signs_the_shared_golden_vectors(string $payload, string $secret, string $timestamp, string $canonical, string $signature): void
	{
		$this->assertSame($signature, WebhookVerifier::computeSignature($secret, $timestamp, $payload));
	}

	#[Test]
	public function it_sorts_keys_at_every_level(): void
	{
		$this->assertSame('{"a":1,"b":2}', WebhookVerifier::canonicalJson('{"b":2,"a":1}'));
		$this->assertSame('{"z":{"x":2,"y":1}}', WebhookVerifier::canonicalJson('{"z":{"y":1,"x":2}}'));
	}

	#[Test]
	public function it_preserves_array_order(): void
	{
		// Arrays are ordered by definition: sorting them would change meaning.
		$this->assertSame('{"items":[3,1,2]}', WebhookVerifier::canonicalJson('{"items":[3,1,2]}'));
	}

	#[Test]
	public function it_keeps_an_empty_object_distinct_from_an_empty_array(): void
	{
		// Decoding with assoc=true would turn {} into [] and change the signed bytes.
		$this->assertSame('{}', WebhookVerifier::canonicalJson('{}'));
		$this->assertSame('[]', WebhookVerifier::canonicalJson('[]'));
		$this->assertSame('{"a":{},"b":[]}', WebhookVerifier::canonicalJson('{"b":[],"a":{}}'));
	}

	#[Test]
	public function it_rejects_invalid_json(): void
	{
		foreach (['{not json', '', '{"a":1', '{"a":01}', "{\"a\":\"\x01\"}", '{"a":1} x', '[1,]', '{"a":1e400}'] as $bad) {
			try {
				WebhookVerifier::canonicalJson($bad);
				$this->fail('Expected ' . json_encode($bad) . ' to be rejected.');
			} catch (ValidationException $e) {
				$this->assertStringContainsString('not valid JSON', $e->getMessage());
			}
		}
	}

	#[Test]
	public function numbers_do_not_depend_on_serialize_precision(): void
	{
		$previous = ini_get('serialize_precision');

		try {
			foreach (['17', '100', '5'] as $precision) {
				ini_set('serialize_precision', $precision);

				$this->assertSame('{"fee":0.1,"price":19.99,"tiny":1e-7}', WebhookVerifier::canonicalJson('{"price":19.99,"fee":0.1,"tiny":1e-7}'));
				$this->assertSame('{"n":0.3}', WebhookVerifier::canonicalJson(['n' => 0.3]));
				$this->assertSame($precision, ini_get('serialize_precision'), 'The setting is restored.');
			}
		} finally {
			ini_set('serialize_precision', (string) $previous);
		}
	}

	#[Test]
	public function strings_follow_go_decoding_rules(): void
	{
		// A high surrogate followed by a non-surrogate escape: U+FFFD, then the next escape.
		$this->assertSame("{\"s\":\"\u{FFFD}A\"}", WebhookVerifier::canonicalJson('{"s":"\ud800\u0041"}'));
		// A valid pair is one character.
		$this->assertSame("{\"s\":\"\u{10000}\"}", WebhookVerifier::canonicalJson('{"s":"\ud800\udc00"}'));
		// Invalid UTF-8 bytes become U+FFFD, one per byte, as Go's decoder does.
		$this->assertSame("{\"s\":\"a\u{FFFD}\u{FFFD}b\"}", WebhookVerifier::canonicalJson("{\"s\":\"a\xE2\x82b\"}"));
		// Duplicate keys: last wins, as in a Go map.
		$this->assertSame('{"a":2}', WebhookVerifier::canonicalJson('{"a":1,"a":2}'));
		// Escaped slashes and whitespace-heavy input canonicalise away.
		$this->assertSame('{"u":"a/b"}', WebhookVerifier::canonicalJson(" { \"u\" :\r\n \"a\\/b\" } "));
	}

	#[Test]
	public function a_decoded_payload_canonicalises_like_the_raw_body(): void
	{
		$raw = '{"b":{},"a":[],"n":-0.0,"big":"1000000000000000000","f":19.99}';

		$this->assertSame(
			WebhookVerifier::canonicalJson($raw),
			WebhookVerifier::canonicalJson(json_decode($raw, false)),
			'Decoding objects as stdClass keeps {} apart from [].',
		);

		// An associative decode cannot tell {} from []; that one ambiguity is documented.
		$this->assertSame(
			'{"a":[],"b":[],"big":"1000000000000000000","f":19.99,"n":-0}',
			WebhookVerifier::canonicalJson(json_decode($raw, true)),
		);
	}

	#[Test]
	public function it_accepts_a_genuine_webhook(): void
	{
		$ts = (string) time();
		$payload = '{"uuid":"pay@abc","txType":"payment"}';
		$sig = WebhookVerifier::computeSignature(self::SECRET, $ts, $payload);

		WebhookVerifier::verify(self::SECRET, $ts, $sig, $payload);
		$this->addToAssertionCount(1);
	}

	#[Test]
	public function it_accepts_a_payload_whose_keys_were_reordered(): void
	{
		$ts = (string) time();
		$sig = WebhookVerifier::computeSignature(self::SECRET, $ts, '{"a":1,"b":2}');

		WebhookVerifier::verify(self::SECRET, $ts, $sig, '{"b":2,"a":1}');
		$this->addToAssertionCount(1);
	}

	#[Test]
	public function it_rejects_a_tampered_payload(): void
	{
		$ts = (string) time();
		$sig = WebhookVerifier::computeSignature(self::SECRET, $ts, '{"uuid":"pay@abc"}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('signature mismatch');
		WebhookVerifier::verify(self::SECRET, $ts, $sig, '{"uuid":"pay@EVIL"}');
	}

	#[Test]
	public function it_rejects_a_tampered_timestamp(): void
	{
		$ts = time();
		$sig = WebhookVerifier::computeSignature(self::SECRET, (string) $ts, '{"a":1}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('signature mismatch');
		WebhookVerifier::verify(self::SECRET, (string) ($ts - 30), $sig, '{"a":1}');
	}

	#[Test]
	public function it_rejects_the_wrong_secret(): void
	{
		$ts = (string) time();
		$sig = WebhookVerifier::computeSignature(self::SECRET, $ts, '{"a":1}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('signature mismatch');
		WebhookVerifier::verify('whsec_wrong', $ts, $sig, '{"a":1}');
	}

	#[Test]
	public function it_rejects_a_replayed_webhook(): void
	{
		$old = (string) (time() - 600);
		$sig = WebhookVerifier::computeSignature(self::SECRET, $old, '{"a":1}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('expired');
		WebhookVerifier::verify(self::SECRET, $old, $sig, '{"a":1}');
	}

	#[Test]
	public function it_rejects_a_future_timestamp(): void
	{
		// Guards against a forged future timestamp extending the replay window.
		$future = (string) (time() + 600);
		$sig = WebhookVerifier::computeSignature(self::SECRET, $future, '{"a":1}');

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('expired');
		WebhookVerifier::verify(self::SECRET, $future, $sig, '{"a":1}');
	}

	#[Test]
	public function it_honours_a_custom_replay_window(): void
	{
		$old = (string) (time() - 600);
		$sig = WebhookVerifier::computeSignature(self::SECRET, $old, '{"a":1}');

		WebhookVerifier::verify(self::SECRET, $old, $sig, '{"a":1}', 1800);
		$this->addToAssertionCount(1);
	}

	#[Test]
	public function it_rejects_a_non_numeric_timestamp(): void
	{
		// Parsed like Go's strconv.ParseInt: no whitespace, no decimals, within int64.
		foreach (['nope', ' 1700000000', '1700000000 ', '1.7e9', '0x10', '99999999999999999999', '-9223372036854775809'] as $bad) {
			try {
				WebhookVerifier::verify(self::SECRET, $bad, 'sha256=abc', '{"a":1}', nowSeconds: 1700000000);
				$this->fail("Expected {$bad} to be rejected.");
			} catch (ValidationException $e) {
				$this->assertSame('webhook timestamp is not a unix-seconds integer', $e->getMessage());
			}
		}
	}

	#[Test]
	public function a_signed_timestamp_is_accepted_like_go(): void
	{
		$timestamp = '+1700000000';
		$signature = WebhookVerifier::computeSignature(self::SECRET, $timestamp, '{"a":1}');

		WebhookVerifier::verify(self::SECRET, $timestamp, $signature, '{"a":1}', nowSeconds: 1700000100);
		$this->addToAssertionCount(1);
	}

	#[Test]
	public function a_non_positive_max_age_means_the_default_window(): void
	{
		$timestamp = '1700000000';
		$signature = WebhookVerifier::computeSignature(self::SECRET, $timestamp, '{"a":1}');

		// 200 s old: inside the default 300 s window, even with maxAge 0 or -1.
		WebhookVerifier::verify(self::SECRET, $timestamp, $signature, '{"a":1}', 0, 1700000200);
		WebhookVerifier::verify(self::SECRET, $timestamp, $signature, '{"a":1}', -1, 1700000200);

		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('expired');

		WebhookVerifier::verify(self::SECRET, $timestamp, $signature, '{"a":1}', 0, 1700000400);
	}

	#[Test]
	public function an_extreme_timestamp_is_rejected_without_overflow(): void
	{
		$this->expectException(ValidationException::class);
		$this->expectExceptionMessage('expired');

		WebhookVerifier::verify(self::SECRET, '-9223372036854775808', 'sha256=abc', '{"a":1}', nowSeconds: PHP_INT_MAX);
	}

	#[Test]
	public function it_extracts_headers_from_a_server_superglobal(): void
	{
		// PHP mangles header names into $_SERVER as HTTP_X_WEBHOOK_*.
		$h = WebhookVerifier::extractHeaders([
			'HTTP_X_WEBHOOK_SIGNATURE_256' => 'sha256=abc',
			'HTTP_X_WEBHOOK_TIMESTAMP' => '1700000000',
			'HTTP_X_WEBHOOK_ID' => 'pay@abc',
			'REQUEST_METHOD' => 'POST',
		]);

		$this->assertSame('sha256=abc', $h['signature']);
		$this->assertSame('1700000000', $h['timestamp']);
		$this->assertSame('pay@abc', $h['webhookId']);
		$this->assertFalse($h['isTest']);
	}

	#[Test]
	public function it_extracts_headers_from_a_psr7_style_array(): void
	{
		$h = WebhookVerifier::extractHeaders([
			'X-Webhook-Signature-256' => ['sha256=abc'],
			'X-Webhook-Timestamp' => ['1700000000'],
			'X-Webhook-Id' => [WebhookVerifier::TEST_WEBHOOK_ID],
		]);

		$this->assertSame('sha256=abc', $h['signature']);
		$this->assertTrue($h['isTest']);
	}

	#[Test]
	public function missing_headers_come_back_empty(): void
	{
		$h = WebhookVerifier::extractHeaders([]);

		$this->assertSame('', $h['signature']);
		$this->assertSame('', $h['timestamp']);
		$this->assertFalse($h['isTest']);
	}
}
